<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $menus = [
            // Dashboard
            [
                'id' => 1,
                'parent_id' => null,
                'name' => 'Dashboard',
                'description' => 'Dashboard',
                'routes' => 'home',
                'icon' => 'ri-dashboard-2-line',
                'sequence' => 1,
                'active' => true,
            ],
            
            // Master Data
            [
                'id' => 2,
                'parent_id' => null,
                'name' => 'Master Data',
                'description' => 'Master Data',
                'routes' => '#',
                'icon' => 'ri-database-2-line',
                'sequence' => 2,
                'active' => true,
            ],
            [
                'id' => 21,
                'parent_id' => 2,
                'name' => 'User Admin',
                'description' => 'Manajemen User Admin',
                'routes' => 'user-admin',
                'icon' => 'ri-user-settings-line',
                'sequence' => 1,
                'active' => true,
            ],
            [
                'id' => 22,
                'parent_id' => 2,
                'name' => 'User Customer',
                'description' => 'Manajemen User Customer',
                'routes' => 'user-customer',
                'icon' => 'ri-user-line',
                'sequence' => 2,
                'active' => true,
            ],
            [
                'id' => 23,
                'parent_id' => 2,
                'name' => 'Package',
                'description' => 'Manajemen Package',
                'routes' => 'package',
                'icon' => 'ri-box-3-line',
                'sequence' => 3,
                'active' => true,
            ],
            [
                'id' => 24,
                'parent_id' => 2,
                'name' => 'Product',
                'description' => 'Manajemen Product',
                'routes' => 'product',
                'icon' => 'ri-product-hunt-line',
                'sequence' => 4,
                'active' => true,
            ],
            [
                'id' => 25,
                'parent_id' => 2,
                'name' => 'Branch',
                'description' => 'Manajemen Branch',
                'routes' => 'branch',
                'icon' => 'ri-building-line',
                'sequence' => 5,
                'active' => true,
            ],
            [
                'id' => 26,
                'parent_id' => 2,
                'name' => 'Category',
                'description' => 'Manajemen Category',
                'routes' => 'category',
                'icon' => 'ri-list-check',
                'sequence' => 6,
                'active' => true,
            ],
            
            // Inventory
            [
                'id' => 3,
                'parent_id' => null,
                'name' => 'Inventory',
                'description' => 'Inventory Management',
                'routes' => '#',
                'icon' => 'ri-archive-line',
                'sequence' => 3,
                'active' => true,
            ],
            [
                'id' => 31,
                'parent_id' => 3,
                'name' => 'Inventory Stock',
                'description' => 'Inventory Stock',
                'routes' => 'inventorystock',
                'icon' => 'ri-stock-line',
                'sequence' => 1,
                'active' => true,
            ],
            [
                'id' => 32,
                'parent_id' => 3,
                'name' => 'Order',
                'description' => 'Order Management',
                'routes' => 'order',
                'icon' => 'ri-shopping-cart-line',
                'sequence' => 2,
                'active' => true,
            ],
            [
                'id' => 33,
                'parent_id' => 3,
                'name' => 'Retur',
                'description' => 'Return Management',
                'routes' => 'retur',
                'icon' => 'ri-arrow-go-back-line',
                'sequence' => 3,
                'active' => true,
            ],
            [
                'id' => 34,
                'parent_id' => 3,
                'name' => 'Transfer Stock',
                'description' => 'Transfer Stock',
                'routes' => 'transfer-stock',
                'icon' => 'ri-truck-line',
                'sequence' => 4,
                'active' => true,
            ],
            [
                'id' => 35,
                'parent_id' => 3,
                'name' => 'Stock',
                'description' => 'Stock Overview',
                'routes' => 'stock',
                'icon' => 'ri-stack-line',
                'sequence' => 5,
                'active' => true,
            ],
            
            // Finance
            [
                'id' => 4,
                'parent_id' => null,
                'name' => 'Finance',
                'description' => 'Finance Management',
                'routes' => '#',
                'icon' => 'ri-money-dollar-circle-line',
                'sequence' => 4,
                'active' => true,
            ],
            [
                'id' => 41,
                'parent_id' => 4,
                'name' => 'Invoice',
                'description' => 'Invoice Management',
                'routes' => 'invoice',
                'icon' => 'ri-file-list-3-line',
                'sequence' => 1,
                'active' => true,
            ],
            [
                'id' => 42,
                'parent_id' => 4,
                'name' => 'Invoice Setting',
                'description' => 'Invoice Setting',
                'routes' => 'invoice-setting',
                'icon' => 'ri-settings-3-line',
                'sequence' => 2,
                'active' => true,
            ],
            [
                'id' => 43,
                'parent_id' => 4,
                'name' => 'Omzet',
                'description' => 'Omzet Report',
                'routes' => 'omzet',
                'icon' => 'ri-line-chart-line',
                'sequence' => 3,
                'active' => true,
            ],
            [
                'id' => 44,
                'parent_id' => 4,
                'name' => 'Omzet Statistic',
                'description' => 'Omzet Statistic',
                'routes' => 'omzet-statistic.index',
                'icon' => 'ri-bar-chart-box-line',
                'sequence' => 4,
                'active' => true,
            ],
            [
                'id' => 45,
                'parent_id' => 4,
                'name' => 'Finance Report',
                'description' => 'Finance Report',
                'routes' => 'finance-report',
                'icon' => 'ri-file-chart-line',
                'sequence' => 5,
                'active' => true,
            ],
            
            // Operational
            [
                'id' => 5,
                'parent_id' => null,
                'name' => 'Operational',
                'description' => 'Operational Management',
                'routes' => '#',
                'icon' => 'ri-tools-line',
                'sequence' => 5,
                'active' => true,
            ],
            [
                'id' => 51,
                'parent_id' => 5,
                'name' => 'Pelanggan',
                'description' => 'Customer Management',
                'routes' => 'pelanggan',
                'icon' => 'ri-user-3-line',
                'sequence' => 1,
                'active' => true,
            ],
            [
                'id' => 52,
                'parent_id' => 5,
                'name' => 'Pemasangan',
                'description' => 'Installation Management',
                'routes' => 'pemasangan',
                'icon' => 'ri-tools-fill',
                'sequence' => 2,
                'active' => true,
            ],
            [
                'id' => 53,
                'parent_id' => 5,
                'name' => 'GiveAway',
                'description' => 'GiveAway Management',
                'routes' => 'giveaway.index',
                'icon' => 'ri-gift-line',
                'sequence' => 3,
                'active' => true,
            ],
            [
                'id' => 54,
                'parent_id' => 5,
                'name' => 'Kurir GiveAway',
                'description' => 'Courier GiveAway',
                'routes' => 'kurir-giveaway',
                'icon' => 'ri-e-bike-2-line',
                'sequence' => 4,
                'active' => true,
            ],
            [
                'id' => 55,
                'parent_id' => 5,
                'name' => 'Data Asset',
                'description' => 'Asset Management',
                'routes' => 'data-asset.index',
                'icon' => 'ri-briefcase-line',
                'sequence' => 5,
                'active' => true,
            ],
            
            // Support
            [
                'id' => 6,
                'parent_id' => null,
                'name' => 'Support',
                'description' => 'Support Management',
                'routes' => '#',
                'icon' => 'ri-customer-service-2-line',
                'sequence' => 6,
                'active' => true,
            ],
            [
                'id' => 61,
                'parent_id' => 6,
                'name' => 'Support Ticket',
                'description' => 'Support Ticket',
                'routes' => 'support_ticket.index',
                'icon' => 'ri-ticket-2-line',
                'sequence' => 1,
                'active' => true,
            ],
            [
                'id' => 62,
                'parent_id' => 6,
                'name' => 'Resolve Ticket',
                'description' => 'Resolve Ticket',
                'routes' => 'resolve_ticket.index',
                'icon' => 'ri-check-double-line',
                'sequence' => 2,
                'active' => true,
            ],
            
            // Attendance
            [
                'id' => 7,
                'parent_id' => null,
                'name' => 'Attendance',
                'description' => 'Attendance Management',
                'routes' => '#',
                'icon' => 'ri-calendar-check-line',
                'sequence' => 7,
                'active' => true,
            ],
            [
                'id' => 71,
                'parent_id' => 7,
                'name' => 'Attendance Monitor',
                'description' => 'Attendance Monitor',
                'routes' => 'attendance_monitor.index',
                'icon' => 'ri-user-voice-line',
                'sequence' => 1,
                'active' => true,
            ],
            
            // Website
            [
                'id' => 8,
                'parent_id' => null,
                'name' => 'Website',
                'description' => 'Website Management',
                'routes' => '#',
                'icon' => 'ri-global-line',
                'sequence' => 8,
                'active' => true,
            ],
            [
                'id' => 81,
                'parent_id' => 8,
                'name' => 'Website Product',
                'description' => 'Website Product',
                'routes' => 'website-product',
                'icon' => 'ri-price-tag-3-line',
                'sequence' => 1,
                'active' => true,
            ],
            [
                'id' => 82,
                'parent_id' => 8,
                'name' => 'Website FAQ',
                'description' => 'Website FAQ',
                'routes' => 'website-faq',
                'icon' => 'ri-question-answer-line',
                'sequence' => 2,
                'active' => true,
            ],
            [
                'id' => 83,
                'parent_id' => 8,
                'name' => 'Website Method',
                'description' => 'Website Method',
                'routes' => 'website-method',
                'icon' => 'ri-layout-line',
                'sequence' => 3,
                'active' => true,
            ],
            [
                'id' => 84,
                'parent_id' => 8,
                'name' => 'Website Partner',
                'description' => 'Website Partner',
                'routes' => 'website-partner',
                'icon' => 'ri-team-line',
                'sequence' => 4,
                'active' => true,
            ],
        ];

        foreach ($menus as $menu) {
            DB::table('menus')->updateOrInsert(
                ['id' => $menu['id']],
                array_merge($menu, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
